name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1  # Set your AWS region

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Plan
      run: terraform apply -auto-approve

    - name: Deploy to ECS
      run: |
        # Use the AWS CLI or Terraform to update ECS service with new task definition
        aws ecs update-service --cluster my-ecs-cluster --service my-service --task-definition my-task-arn

    - name: Cleanup
      run: terraform destroy -auto-approve
      if: always()
